spring:
  application:
    # sets the name in Eureka & Zipkin
    name: zuul-server
  # show the /routes output in a formatted (prettier) way
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8090

zuul:
  prefix: /services

## to retrieve all configured Zuul routes at the /routes endpoint, we have to disable spring.boot.actuator´s authentication requirement
#management:
#  security:
#    enabled: false

## Switch Eureka-Usage on & off
#ribbon:
#  eureka:
#    enabled:

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true

## Increase the Hystrix timeout to 60s (globally)
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

## No ugly logging pollution, if Eureka isn´t up or found
#logging:
#  level:
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF